//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1760172_1760180
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public int ID { get; set; }
        public int ID_HOADON { get; set; }
        public int ID_SANPHAM { get; set; }
        public int SOLUONG { get; set; }
        public double GIA { get; set; }
        public double THANHTIEN { get; set; }
    }
}
