//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1760172_1760180
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOATDONGKHO
    {
        public int ID { get; set; }
        public int IDSP { get; set; }
        public string HOATDONG { get; set; }
        public int SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAYHD { get; set; }
    }
}
