//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1760172_1760180
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public int ID { get; set; }
        public int SLTON { get; set; }
        public int SLDABAN { get; set; }
    }
}
