//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1760172_1760180
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int ID { get; set; }
        public string TENSP { get; set; }
        public int LOAISP { get; set; }
        public int NHANHANG { get; set; }
        public double GIA { get; set; }
        public byte[] ANH { get; set; }
    }
}
